/radar/pc_aligner:
  ros__parameters:
    sample_lidar: 'lidar_mid70'
    # 初始化采样点云数目
    init_sample: 1000000
    # 对齐器采样模型点数
    mesh_sample: 1000000
    # 对齐器裁剪盒 单位: m
    crop_box.min: [0.5, 0.150, -0.2]
    crop_box.max: [27.5, 14.850, 1.5]
    # 最大对应点距离 单位: m
    max_corr_dist: 0.5
    # 最大迭代次数
    max_iteration: 20
    # 启用预选择点
    use_preselect: True
    # 启动时手动对齐
    startup_manual_align: True

    vis_auto: True

    manual_crop.min: [0., -10., -10.]
    manual_crop.max: [30., 15., 10.]

    mesh: "rm_2026_19M.stl"

/radar/hik_6mm/hik_camera:
  ros__parameters:
    frame_rate: 30.0

/radar/judge_bridge:
  ros__parameters:
    enable_recorder: True

